# Generated by Django 2.2.7 on 2019-11-07 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='current_round',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contest',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contest',
            name='round_nums',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contest',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juror',
            name='password',
            field=models.CharField(default='password', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juror',
            name='username',
            field=models.CharField(default='juror0', max_length=32),
            preserve_default=False,
        ),
    ]
