# Generated by Django 2.2.7 on 2019-11-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191107_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='round',
        ),
        migrations.AddField(
            model_name='juror',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='contests',
            field=models.ManyToManyField(to='api.Contest'),
        ),
        migrations.AddField(
            model_name='participant',
            name='serie',
            field=models.ManyToManyField(to='api.Series'),
        ),
        migrations.AddField(
            model_name='participant',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='series_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
