# Generated by Django 2.2.7 on 2019-11-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191110_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='rounds',
            field=models.ManyToManyField(to='api.Round'),
        ),
    ]
