# Generated by Django 2.2.7 on 2019-11-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_participant_rounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='series_no',
            field=models.IntegerField(null=True),
        ),
    ]
