# Generated by Django 2.2.7 on 2019-11-10 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191110_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='rounds',
            new_name='round',
        ),
    ]
