# Generated by Django 2.2.7 on 2019-11-11 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191110_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ritm', models.IntegerField(null=True)),
                ('coregrafie', models.IntegerField(null=True)),
                ('corectitudine', models.IntegerField(null=True)),
                ('componentaArtistica', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='juror',
            name='vote',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='nota',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='vote',
            field=models.IntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='participant',
            name='serie',
        ),
        migrations.AddField(
            model_name='participant',
            name='serie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Series'),
            preserve_default=False,
        ),
    ]
