# Generated by Django 2.2.7 on 2019-11-11 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191111_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Series'),
        ),
    ]
