# Generated by Django 2.2.7 on 2019-11-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20191111_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='jurors_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
