# Generated by Django 2.2.7 on 2019-11-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_contest_jurors_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='jurors_no',
            field=models.IntegerField(null=True),
        ),
    ]
