# Generated by Django 2.2.7 on 2019-11-11 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191111_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='jurat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Juror'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='participant_id',
            field=models.IntegerField(null=True),
        ),
    ]
