# Generated by Django 2.2.7 on 2019-11-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191111_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='jurat',
            field=models.CharField(max_length=32),
        ),
    ]
