# Generated by Django 2.2.7 on 2019-11-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20191111_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='contest_id',
            field=models.IntegerField(null=True),
        ),
    ]
