# Generated by Django 2.2.7 on 2019-11-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_note_contest_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='category',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='juror',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='series',
        ),
        migrations.AddField(
            model_name='grade',
            name='ritm',
            field=models.IntegerField(null=True),
        ),
    ]
