# Generated by Django 2.2.7 on 2019-11-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_grade_coregrafie'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='componentaArtistica',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='corectitudine',
            field=models.IntegerField(null=True),
        ),
    ]
