# Generated by Django 2.2.7 on 2019-11-13 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20191113_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='contest_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Contest'),
        ),
    ]
