# Generated by Django 2.2.7 on 2019-11-13 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_grade_contest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Contest'),
        ),
    ]
