# Generated by Django 2.2.7 on 2019-11-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_series_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='allow',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
