# Generated by Django 2.2.7 on 2019-11-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_round_allow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='current_round',
            field=models.IntegerField(null=True),
        ),
    ]
