# Generated by Django 2.2.7 on 2019-11-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20191113_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='whoVoted',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='eliminate',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
