# Generated by Django 2.2.7 on 2019-11-17 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20191117_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='nota',
            field=models.FloatField(null=True),
        ),
        migrations.RemoveField(
            model_name='participant',
            name='round',
        ),
        migrations.AddField(
            model_name='participant',
            name='round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Round'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.IntegerField(default='1', null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='vote',
            field=models.IntegerField(default='1', null=True),
        ),
    ]
