# Generated by Django 2.2.7 on 2019-11-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20191117_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='whoVoted',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
