# Generated by Django 2.2.7 on 2019-11-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20191118_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='vote',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
