# Generated by Django 2.2.7 on 2019-11-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20191118_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='vote',
            field=models.IntegerField(null=True),
        ),
    ]
