# Generated by Django 2.2.7 on 2019-11-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20191118_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='jurors_no',
        ),
        migrations.RemoveField(
            model_name='juror',
            name='status',
        ),
        migrations.RemoveField(
            model_name='juror',
            name='vote',
        ),
        migrations.AddField(
            model_name='juror',
            name='allow',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='current_round',
            field=models.IntegerField(default='1', null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='nota',
            field=models.FloatField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.IntegerField(default='1', null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='vote',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='whoVoted',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='allow',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
